version: "3.8"
services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: jitendra
      POSTGRES_PASSWORD: jitendra123
      POSTGRES_DB: studykaro
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:/var/lib/postgresql/data
